# wrangler.toml
name = "secureonev2"
main = "_worker.js"
compatibility_date = "2025-10-18"
workers_dev = true

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true
